NomadEcommerce.Coffee/Controllers/CoffeeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NomadEcommerce.Coffee.DataContext;
using NomadEcommerce.Coffee.Models;

namespace NomadEcommerce.Coffee.Controllers
{
    public class CoffeeController : Controller
    {
        private readonly CoffeeDBContext _context;

        public CoffeeController(CoffeeDBContext context)
        {
            _context = context;
        }

        // GET: Coffee
        public async Task<IActionResult> Index()
        {
            return View(await _context.CoffeeModels.Include(x => x.Images).ToListAsync());
        }

        // GET: Coffee/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coffeeModel = await _context.CoffeeModels.Include(x=>x.Images)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (coffeeModel == null)
            {
                return NotFound();
            }

            return View(coffeeModel);
        }

        // GET: Coffee/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Coffee/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Type,ImageFile")] CoffeeModel coffeeModel)
        {
            if (ModelState.IsValid)
            {
                if (coffeeModel.ImageFile != null && coffeeModel.ImageFile.Length > 0)
                {
                    var extension = Path.GetExtension(coffeeModel.ImageFile?.FileName);
                    var size = coffeeModel.ImageFile?.Length;
                    if (!extension.ToLower().Equals(".png"))
                    {
                        ModelState.AddModelError("ImageFile", "Only png files are allowed");
                        return View(coffeeModel);
                    }

                    if (size > (50 * 1024))
                    {
                        ModelState.AddModelError("ImageFile", "File size is bigger than 50 KB.");
                        return View(coffeeModel);
                    }

                    using (var memoryStream = new MemoryStream())
                    {
                        await coffeeModel.ImageFile.CopyToAsync(memoryStream);
                        byte[] bytes = memoryStream.ToArray();
                        string base64String = Convert.ToBase64String(bytes, 0, bytes.Length);
                        coffeeModel.Images = new List<CoffeeImageModel>
                        {
                            new CoffeeImageModel { Data = "data:image/png;base64," + base64String }
                        };
                    }
                }

                _context.Add(coffeeModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(coffeeModel);
        }

        // GET: Coffee/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coffeeModel = await _context.CoffeeModels.FindAsync(id);
            if (coffeeModel == null)
            {
                return NotFound();
            }
            return View(coffeeModel);
        }

        // POST: Coffee/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Type,Replace,ImageFile")] CoffeeModel coffeeModel)
        {
            if (id != coffeeModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(coffeeModel);
                    await _context.SaveChangesAsync();
                    if (coffeeModel.ImageFile != null && coffeeModel.ImageFile.Length > 0)
                    {
                        var extension = Path.GetExtension(coffeeModel.ImageFile?.FileName);
                        var size = coffeeModel.ImageFile?.Length;
                        if (!extension.ToLower().Equals(".png"))
                        {
                            ModelState.AddModelError("ImageFile", "Only png files are allowed");
                            return View(coffeeModel);
                        }

                        if (size > (50 * 1024))
                        {
                            ModelState.AddModelError("ImageFile", "File size is bigger than 50 KB.");
                            return View(coffeeModel);
                        }

                        using (var memoryStream = new MemoryStream())
                        {
                            await coffeeModel.ImageFile.CopyToAsync(memoryStream);
                            byte[] bytes = memoryStream.ToArray();
                            string base64String = Convert.ToBase64String(bytes, 0, bytes.Length);
                            var existing = await _context.CoffeeModels.Include(x => x.Images).FirstOrDefaultAsync(x => x.Id == id);
                            if (coffeeModel.Replace)
                            {
                                existing.Images.Clear();
                                await _context.SaveChangesAsync();
                            }
                            existing.Images.Add(new CoffeeImageModel { Data = "data:image/png;base64," + base64String });
                            await _context.SaveChangesAsync();
                        }
                    }
                    
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CoffeeModelExists(coffeeModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(coffeeModel);
        }

        // GET: Coffee/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coffeeModel = await _context.CoffeeModels
                .FirstOrDefaultAsync(m => m.Id == id);
            if (coffeeModel == null)
            {
                return NotFound();
            }

            return View(coffeeModel);
        }

        // POST: Coffee/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var coffeeModel = await _context.CoffeeModels.FindAsync(id);
            _context.CoffeeModels.Remove(coffeeModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CoffeeModelExists(int id)
        {
            return _context.CoffeeModels.Any(e => e.Id == id);
        }
    }
}

NomadEcommerce.Coffee/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NomadEcommerce.Coffee</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Coffee" asp-action="Index">NomadEcommerce.Coffee</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Coffee" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - NomadEcommerce.Coffee
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>